browser-tests: debugging playwright cookie
opstrace/opstrace pull request #1165
Opened 2021-08-03 05:34 UTC by terrcin

Have the Playwright browser tests set a special `opstrace-playwright` cookie the react app can read. When set the `AccessDenied` page will show extra error info sent from the server which should be included in test failure screenshots.

2021-08-03 19:06 UTC, MatApple requested changes

2021-08-03 19:06 UTC, MatApple commented on packages/app/src/client/components/withSession/pages/AccessDenied.tsx
> +  const isPlaywright = Cookies.get("opstrace-playwright");
Let's sync about this before we merge. Why do we need to use a cookie? 

The bit I'm missing is why we can't just send the error we get from Auth0 (or any other server-side error) back to the UI and then use the appropriate Error component to show the error. In the case of a 403, we use the AccessDenied component, but for all other errors we could just use our ErrorView component

2021-08-04 12:25 UTC, jgehrcke commented
> When set the AccessDenied page will show extra error info sent from the server which should be included in test failure screenshots.

I agree with @MatApple that maybe we do not want to have this asymmetry between CI env and prod env. If this is about debuggability, there are two more things we can do:

- We have the collections cluster to inspect the API's logs. How to use that I have shown here: https://github.com/opstrace/opstrace/issues/1137#issuecomment-891082681.

- If that is a little too much work, we can use the approach in https://github.com/opstrace/opstrace/blob/8af9e91d27f8f8056cda1364cc587a8f3d39e579/ci/create-cluster-artifacts.sh to pull the API container logs straight into the BK artifacts.

2021-08-10 03:14 UTC, terrcin commented
not doing this change

2021-08-10 03:14 UTC, closed without merging