Mosattler/refactor ringhealth
opstrace/opstrace pull request #828
Opened 2021-06-03 09:59 UTC by MoSattler

Based on #827 

# Have you...

* [ ] Discussed your change with a project contributor in an issue yet?
* [ ] Added an explanation of what your changes do?
* [ ] Written new tests for your changes?
* [ ] Thought about which docs need updating?

2021-06-03 18:32 UTC, MatApple requested changes

2021-06-03 18:32 UTC, MatApple commented on packages/app/src/client/views/ring-health/RingHealth.tsx
> +        <Typography variant="h1">Cortex Ring Health</Typography>
You also need to pass in the title here as a prop

2021-06-04 08:39 UTC, MoSattler commented
@MatApple [fixed](https://github.com/opstrace/opstrace/pull/828/commits/8619da6471dd006c8e4fd21fc45adb68c3594117)

2021-06-04 20:43 UTC, MatApple approved these changes

2021-06-04 20:43 UTC, merged